import { techStack } from "./techstack";

type TechStackItem = (typeof techStack)[keyof typeof techStack];
export type ProjectData = {
  id: number;
  name: string;
  href: string;
  live: string;
  featured: boolean;
  createdAt: string;
  banner: string;
  description: string;
  features: string[];
  technologies: TechStackItem[];
};

export const allProjects: ProjectData[] = [
  {
    id: 1,
    name: "Tweetz",
    href: "https://tweetz.app/",
    live: "https://tweetz.app/",
    createdAt: "20-08-2025",
    featured: true,
    banner: "/project_banners/tweetz_banner.png",
    description:
      "Tweetz.app is an AI-assisted Twitter posting with one-tap Telegram approvals with learning and editing features",
    features: [
      "Better Auth authentication including sign up, sign in, and logout",
      "Have 7 Day free trial, No credit card required",
      "Auto Geneate Tweets based on your prefrences on daily basis",
      "Learns your tone so well, even your mom won't know the difference. (Fully editable, in case our AI gets too sassy.)",
      "Stay in control from your couch, your commute, or that awkward elevator ride.",
      "Set it and forget it. Like a crockpot, but for your Twitter presence.",
      "Your content goes live exactly when planned. No more 'Did I post that?' panic attacks at 2 AM.",
      "Data stored in Neon PostgreSQL and managed with Prisma ORM",
      "Efficient data fetching using Tanstack Query",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.nodejs,
      techStack.express,
      techStack.postgres,
      techStack.shadcnui,
      techStack.tanstackquery,
      techStack.oauth,
      techStack.prisma,
      techStack.openai,
    ],
  },
  {
    id: 2,
    name: "Snapgroov",
    href: "https://github.com/taqui-786/Snapgroove",
    live: "https://snapgroov.vercel.app/",
    createdAt: "09-12-2025",
    featured: true,
    banner: "/project_banners/snapgroov_banner.png",
    description:
      "Make your screenshots look less like a cry for help. Add shadows, gradients, and device frames in one click. It’s the easiest way to make your work look expensive.",
    features: [
      "Add shadows, gradients, and device frames in one click",
      "Supports multiple devices",
      "No sign-up, no credit card required No limits",
      "smooth image export in you device",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.tailwindcss,
      techStack.shadcnui,
    ],
  },
  {
    id: 3,
    name: "Wryte",
    href: "https://github.com/taqui-786/Wryte",
    live: "https://wryte-ti.vercel.app/",
    createdAt: "01-12-2025",
    featured: true,
    banner: "/project_banners/wryte_banner.png",
    description:
      "Wryte is an AI-powerered blog/content writting platform, it have its own WYSIWYG Ai-editor and be in user tone with various feature such as Auto-complete, next word suggestion, spelling check etc... ",
    features: [
      "Better Auth authentication including sign up, sign in, and logout",
      "It is completely Free but have some limit on Ai features",
      "User can write their content and format it to popular blog platform like Dev.to , medium etc...",
      "Have Various Ai features like Auto complete, Next word suggestion, spelling check etc...",
      "User can share and collaborate workspace with others ",
      "Also direct share the written content with other in just a Readable format",
      "Data stored in Neon PostgreSQL and managed with Drizzle ORM",
      "Efficient data fetching using Tanstack Query",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.oauth,
      techStack.drizzle,
      techStack.openai,
      techStack.tailwindcss,
      techStack.shadcnui,
      techStack.tanstackquery,
      techStack.etc,
    ],
  },
  {
    id: 4,
    name: "PDFlow",
    href: "https://github.com/taqui-786/PDFlow",
    live: "https://pdflow-free.vercel.app/",
    createdAt: "12-07-2025",
    featured: true,
    banner: "/project_banners/pdflow_banner.png",
    description:
      "Transform the way you interact with documents. Our AI-powered platform allows you to upload PDF files and have intelligent conversations with them, extract key insights, and analyze content effortlessly.",
    features: [
      "Document Summarization - Automatically generate concise summaries of your PDF documents",
      "Key Points Extraction - Extract and highlight the most important points from your documents",
      "Important Questions - Generate relevant questions based on your document content",
      "Named Entities - Identify people, organizations, locations, and dates in your documents ",
      "Keywords Extraction - Find the most important keywords and phrases in your content",
      "Interactive Chat - Have natural conversations with your PDF documents",
      "Lucia-auth authentication including sign up, sign in, and logout",
      "Data stored in Neon PostgreSQL and managed with Drizzle ORM",
      "Efficient data fetching using Tanstack Query",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.drizzle,
      techStack.tailwindcss,
      techStack.shadcnui,
      techStack.tanstackquery,
    ],
  },
  {
    id: 5,
    name: "WePost",
    href: "https://github.com/taqui-786/WePost",
    live: "https://wepost.vercel.app",
    createdAt: "09-03-2025",
    banner: "/project_banners/wepost_banner.png",
    featured: false,
    description:
      "WePost is a modern and minimalistic social media platform enabling users to share posts, connect, and engage in discussions. It delivers a seamless and secure experience using the latest web technologies.",
    features: [
      "User authentication including sign up, sign in, and logout",
      "Create, edit, and delete posts",
      "Like and comment functionality on posts",
      "Customizable user profiles",
      "Responsive user interface design",
      "Built with Next.js 15 framework",
      "Authentication powered by Lucia",
      "Data stored in Neon PostgreSQL and managed with Prisma ORM",
      "Efficient data fetching using Tanstack Query",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.prisma,
      techStack.tailwindcss,
      techStack.shadcnui,
      techStack.tanstackquery,
    ],
  },
  {
    id: 6,
    name: "itZmyLink",
    href: "https://github.com/taqui-786/itZmyLink",
    live: "https://itzmylink.vercel.app/",
    featured: false,
    createdAt: "14-10-2023",
    banner: "/project_banners/itzmylink_banner.png",
    description:
      "Your all-in-one link management solution, itZmyLink allows you to create personalized link pages, manage multiple links, and track performance effortlessly. Perfect for social media profiles, business cards, and more.",
    features: [
      "Create and manage personalized link pages",
      "Add multiple links to a single page",
      "Track link performance with analytics",
      "Customizable themes and styles",
      "User-friendly interface for easy navigation",
      "Built with Next.js 14 framework",
      "Authentication powered by Next-Auth",
      "Data stored in Supabase",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.tailwindcss,
      techStack.shadcnui,
    ],
  },
  {
    id: 55,
    name: "Inkash",
    href: "https://github.com/taqui-786/inkash",
    live: "https://inkash.vercel.app",
    featured: false,
    createdAt: "07-02-2025",
    banner: "/project_banners/inkash_banner.png",
    description:
      "Inkash (Ink + Hash) is a beautifully simple web app that lets you create Markdown documents or freehand Canvas drawings — and stores everything directly in the URL. No sign-ups, no cloud storage, no cookies. Your content is the link.",
    features: [
      "High-level Markdown editor with intuitive interface",
      "URL Storage - Your entire document is compressed and encoded into the URL hash. The link IS your file",
      "Instant Sharing - No uploading. No waiting. Just copy the URL and send it — the recipient sees exactly what you created",
      "Zero Accounts - No login. No email. No tracking. Completely anonymous and private",
      "Offline Ready - Works without internet once loaded. Your browser caches everything",
      "QR Code Sharing - Generate a QR code for any document — perfect for sharing on mobile or presentations",
      "Export Options - Download your work as HTML, TXT (Markdown) or PNG, SVG (Canvas)",
      "Dark Mode - Automatic system theme detection with beautiful light and dark modes",
      "Built with Next.js 15 framework",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.tailwindcss,
      techStack.shadcnui,
    ],
  },
  {
    id: 15,
    name: "Portfolio v2",
    href: "https://github.com/taqui-786/portfolio_v2",
    live: "https://taqui-imam.vercel.app",
    createdAt: "17-06-2025",
    featured: false,
    banner: "/project_banners/portfolio_v2_banner.png",
    description:
      "My second personal portfolio website showcasing my skills, projects, and experience. The site is designed to be clean, responsive, and engaging with smooth animations and a modern design.",
    features: [
      "Responsive design that adapts seamlessly to desktops, tablets, and mobile devices",
      "Dark/Light mode theme switching for user preference",
      "Interactive profile section with animated text flipper showcasing roles",
      "Collapsible accordions for detailed experience and projects information",
      "User-friendly contact form with Nodemailer email integration",
      "Social media profile links for easy access",
      "Built with Next.js 15 framework",
      "Form handling with React Hook Form and Zod validation",
      "Smooth animations powered by Framer Motion",
      "Modern UI components styled with Shadcn UI and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.tailwindcss,
      techStack.shadcnui,
    ],
  },
  {
    id: 7,
    name: "Portfolio V1",
    href: "https://github.com/taqui-786/Portfolio",
    live: "https://mdtaquiimam.vercel.app/",
    createdAt: "15-11-2023",
    featured: false,
    banner: "/project_banners/portfolio_v1_banner.png",
    description:
      "My firstpersonal portfolio website showcasing my skills, projects, and experiences. Built with modern web technologies to provide a seamless user experience and highlight my work effectively.",
    features: [
      "Responsive design for all devices",
      "Showcase of my projects with detailed descriptions",
      "Integration with GitHub for project links",
      "Contact form for inquiries",
      "Built with Next.js 15 framework",

      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.tailwindcss,
      techStack.shadcnui,
    ],
  },
  {
    id: 8,
    name: "Mixcn Ui",
    href: "https://github.com/taqui-786/mixcnui",
    live: "https://mixcn-ui.vercel.app/",
    createdAt: "16-06-2024",
    featured: false,
    banner: "/project_banners/mixcnui_banner.png",
    description:
      "A modern UI component library built with Tailwind CSS and Shadcn UI, Mixcn UI provides a set of customizable and reusable components for building responsive web applications.",
    features: [
      "Collection of UI components for web applications",
      "User can integrate components easily with my own npx command",
      "Supports dark mode and light mode themes",
      "Responsive design for all devices",
      "Customizable components for various use cases",
      "Built with Next.js 15 framework",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.tailwindcss,
      techStack.shadcnui,
    ],
  },
  {
    id: 9,
    name: "Devletter",
    href: "https://github.com/taqui-786/Devletter",
    live: "https://devletter.vercel.app/",
    createdAt: "22-11-2023",
    featured: false,
    banner: "/project_banners/devletter_banner.png",
    description:
      "Devletter is a newsletter platform for developers, allowing users to subscribe to newsletters and get the latest updates on various topics. It provides a user-friendly interface for managing subscriptions and reading newsletters.",
    features: [
      "Subscribe to newsletters",
      "Beautiful snow animation effect",
      "Read newsletters with a clean and minimalistic design",
      "Responsive user interface design",
      "Built with Next.js 15 framework",
      "Data stored in Supabase",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.prisma,
      techStack.tailwindcss,
      techStack.shadcnui,
    ],
  },
  {
    id: 10,
    name: "Carousel Maker",
    href: "https://github.com/taqui-786/crousal-maker",
    live: "https://crousal-maker.vercel.app/",
    createdAt: "09-12-2023",
    featured: false,
    banner: "/project_banners/carousel_banner.png",
    description:
      "Carousel maker is a simple carousel editing platform with in-built carousel templates only you can edit heading, descriptions and Images and download it in both format PDF and JPEG.",
    features: [
      "Create and edit carousels with ease",
      "Choose from a variety of templates all FREE",
      "Edit carousel headings, descriptions, and images",
      "Download carousels in PDF and JPEG formats",
      "User-friendly interface for easy editing",
      "Built with Next.js 14 framework",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.tailwindcss,
      techStack.shadcnui,
    ],
  },
  {
    id: 11,
    name: "Friendz",
    href: "https://github.com/taqui-786/project-friendz",
    live: "https://friendz.vercel.app/",
    banner: "/project_banners/friendz_banner.png",
    createdAt: "16-08-2023",
    featured: false,
    description:
      "Friendz is a social media platform that allows users to connect with friends, share updates, and engage in discussions. It provides a user-friendly interface for managing friendships and interactions.",
    features: [
      "Connect with friends",
      "Share updates and posts",
      "Engage in discussions",
      "User-friendly interface",
      "Authentication powered by Next-Auth",
      "Built with Next.js 14 framework",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.prisma,
      techStack.redis,
      techStack.tailwindcss,
      techStack.shadcnui,
    ],
  },
  {
    id: 12,
    name: "GitEstimate",
    href: "https://github.com/taqui-786/GitEstimate",
    live: "https://gitestimate.vercel.app/",
    createdAt: "09-12-2023",
    featured: false,
    banner: "/project_banners/gitestimate_banner.png",
    description:
      "GitEstimate is a FUN tool that helps developers estimate the time required to complete tasks based on their GitHub activity. It provides insights into productivity and helps in planning work effectively.",
    features: [
      "Estimate task completion time",
      "Analyze GitHub activity",
      "Get insights into productivity",
      "Plan work effectively",
      "User-friendly interface",
      "Built with Next.js 14 framework",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.tailwindcss,
      techStack.shadcnui,
    ],
  },
  {
    id: 13,
    name: "FormCraft",
    href: "https://github.com/taqui-786/formcraft",
    live: "https://formcraft-ti.vercel.app/",
    createdAt: "25-08-2024",
    featured: false,
    banner: "/project_banners/formcraft_banner.png",
    description:
      "FormCraft is a powerful tool for developers to create forms in GUI and copy the code to use in their projects. It provides a drag-and-drop interface for building forms and managing submissions.",
    features: [
      "Drag-and-drop form builder",
      "Customizable form fields",
      "Copy and paste code for easy integration",
      "React Hook Form integration for form validation",
      "User-friendly interface",
      "Built with Next.js 14 framework",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.tailwindcss,
      techStack.shadcnui,
    ],
  },

  {
    id: 14,
    name: "Devzone",
    href: "https://github.com/taqui-786/Devzone",
    live: "https://devzone-ti.vercel.app/",
    createdAt: "03-11-2024",
    featured: false,
    banner: "",
    description:
      "DevZone is an innovative platform designed to connect developers, fostering collaboration and knowledge sharing within the tech community. It offers a space for developers to showcase their skills, share projects, and engage in discussions.",
    features: [
      "Developer Profiles: Create and customize your developer profile",
      "Project Showcase: Share your projects and get feedback from peers",
      "Collaborative Coding: Real-time code collaboration tools",
      "Community Forums: Engage in discussions on various tech topics",
      "Resource Sharing: Share and discover valuable developer resources",
      "Job Board: Find opportunities or hire talent within the community",
      "Built with Next.js 14 framework",
      "Modern UI components styled with shadcn-ui and Tailwind CSS",
    ],
    technologies: [
      techStack.nextjs,
      techStack.typescript,
      techStack.tailwindcss,
      techStack.shadcnui,
      techStack.tanstackquery,
    ],
  },
];
