import {
  JavascriptIcon,
  Auth0Icon,
  BunIcon,
  DrizzleIcon,
  TypescriptIcon,
  NextjsIcon,
  NodejsIconIcon,
  NestjsIcon,
  ReactQueryIcon,
  ReduxIcon,
  ReactRouterIcon,
  ReactnavigationIcon,
  ShadcnuiIcon,
  TailwindcssIcon,
  FileTypeReactjsIcon,
  GitIcon,
  DockerIcon,
  MysqlDarkIcon,
  MongodbIcon,
  RedisIcon,
  PostgresqlIcon,
  PrismaIcon,
  OpenaiIcon,
  SupabaseIcon,
  ExpressIcon,
  FigmaIcon,
  PostmanIcon,
  NginxIcon,
  GithubActionsIcon,
  PointIcon,PythonIcon,FastapiIcon
} from "@/components/customIcons";

export const techStack = {
  javascript: {
    name: "JavaScript",
    icon: JavascriptIcon,
    link: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
  },
  typescript: {
    name: "TypeScript",
    icon: TypescriptIcon,
    link: "https://www.typescriptlang.org/",
  },
  reactjs: {
    name: "Reactjs",
    icon: FileTypeReactjsIcon,
    link: "https://react.dev/",
  },
  python: {
    name: "Python",
    icon: PythonIcon,
    link: "https://www.python.org/",
  },
  fastapi: {
    name: "FastAPI",
    icon: FastapiIcon,
    link: "https://fastapi.tiangolo.com/",
  },
  nextjs: { name: "Nextjs", icon: NextjsIcon, link: "https://nextjs.org/" },
  nodejs: { name: "Nodejs", icon: NodejsIconIcon, link: "https://nodejs.org/" },
  nestjs: { name: "NestJs", icon: NestjsIcon, link: "https://nestjs.com/" },
  supabase: {
    name: "Supabase",
    icon: SupabaseIcon,
    link: "https://supabase.com/",
  },

  tailwindcss: {
    name: "TailwindCSS",
    icon: TailwindcssIcon,
    link: "https://tailwindcss.com/",
  },
  shadcnui: {
    name: "Shadcn Ui",
    icon: ShadcnuiIcon,
    link: "https://ui.shadcn.com/",
  },
  oauth: { name: "OAuth", icon: Auth0Icon, link: "https://oauth.net/" },
  tanstackquery: {
    name: "TanStack Query",
    icon: ReactQueryIcon,
    link: "https://tanstack.com/query/latest",
  },
  reactredux: {
    name: "React-Redux",
    icon: ReduxIcon,
    link: "https://react-redux.js.org/",
  },
  reactrouter: {
    name: "React-Router",
    icon: ReactRouterIcon,
    link: "https://reactrouter.com/",
  },
  reactnavigation: {
    name: "React-Navigation",
    icon: ReactnavigationIcon,
    link: "https://reactnavigation.org/",
  },
  git: { name: "Git", icon: GitIcon, link: "https://git-scm.com/" },
  docker: { name: "Docker", icon: DockerIcon, link: "https://www.docker.com/" },
  mysql: {
    name: "My Sql",
    icon: MysqlDarkIcon,
    link: "https://www.mysql.com/",
  },
  mongodb: {
    name: "MongoDB",
    icon: MongodbIcon,
    link: "https://www.mongodb.com/",
  },
  redis: { name: "Redis", icon: RedisIcon, link: "https://redis.io/" },
  postgres: {
    name: "Postgres",
    icon: PostgresqlIcon,
    link: "https://www.postgresql.org/",
  },
  prisma: {
    name: "Prisma ORM",
    icon: PrismaIcon,
    link: "https://www.prisma.io/",
  },
  drizzle: {
    name: "Drizzle ORM",
    icon: DrizzleIcon,
    link: "https://orm.drizzle.team/",
  },
  openai: { name: "Chat GPT", icon: OpenaiIcon, link: "https://openai.com/" },
  express: { name: "Express", icon: ExpressIcon, link: "https://expressjs.com/" },
  figma: { name: "Figma", icon: FigmaIcon, link: "https://figma.com/" },
  postman: { name: "Postman", icon: PostmanIcon, link: "https://www.postman.com/" },
  nginx: { name: "Nginx", icon: NginxIcon, link: "https://www.nginx.com/" },
  githubactions: { name: "Github Actions", icon: GithubActionsIcon, link: "https://www.nginx.com/" },
  bun: { name: "Bun", icon: BunIcon, link: "https://bun.sh/" },
  etc: { name: "And Many More", icon: PointIcon, link: "https://example.com" },
  
};
